#!/usr/bin/env python3
"""
Generate docs/Player_Facing_Metrics_and_Equations.pdf
Player-facing metrics + equations (tracks + homography; no ball).
Uses fpdf2 (Latin-1 safe text only).
"""
from __future__ import annotations

from pathlib import Path


def _t(s: str) -> str:
    return s.encode("latin-1", "replace").decode("latin-1")


def main() -> Path:
    from fpdf import FPDF

    root = Path(__file__).resolve().parents[1]
    out = root / "docs" / "Player_Facing_Metrics_and_Equations.pdf"
    out.parent.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.set_margins(14, 14, 14)
    pdf.set_auto_page_break(auto=True, margin=14)
    text_w = pdf.w - pdf.l_margin - pdf.r_margin
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(text_w, 8, _t("CourtFlow - Player-facing metrics and equations"))
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    intro = (
        "Scope: metrics derived from player tracks only (detection + tracking + homography). "
        "Each track row has court coordinates (x_court, y_court) after calibration. "
        "Padel court constants W = 10 m, H = 20 m for path length in meters (Tier 1 / Tier 2). "
        "No ball model is required for these equations."
    )
    pdf.multi_cell(text_w, 5, _t(intro))
    pdf.ln(3)

    def sec(title: str) -> None:
        if pdf.get_y() > 250:
            pdf.add_page()
        pdf.set_font("Helvetica", "B", 11)
        pdf.multi_cell(text_w, 6, _t(title))
        pdf.set_font("Helvetica", "", 9)

    def blk(body: str) -> None:
        pdf.multi_cell(text_w, 5, _t(body))
        pdf.ln(1)

    sec("Notation")
    blk(
        "p = player id. i = 1..N_p time-ordered samples with valid (x_court, y_court). "
        "L_i = segment length in meters between samples i-1 and i. "
        "dt_i = time between samples (timestamps, else (frame_i - frame_{i-1}) / fps). "
        "D_p = total distance (m). T_p = active duration (s)."
    )

    sec("1) Distance (m), distance_m")
    blk("L_i = sqrt((W * (x_i - x_{i-1}))^2 + (H * (y_i - y_{i-1}))^2)")
    blk("D_p = sum over i=2..N_p of L_i (skip if endpoint missing).")

    sec("2) Tracked time (s), active_duration_s")
    blk("T_p = t_last - t_first using timestamps; else (max_frame - min_frame) / fps.")

    sec("3) Average speed (km/h), avg_speed_kmh")
    blk("v_avg = D_p / T_p  (m/s).  km/h = 3.6 * v_avg. (Path average, not mean of segment speeds.)")

    sec("4) Fastest burst (km/h), max_speed_kmh")
    blk("v_i = L_i / dt_i for each segment. v_hat_i = min(v_i, 12 m/s). max km/h = 3.6 * max_i(v_hat_i).")

    sec("5) Sprint count, sprint_count")
    blk(
        "Segment is sprint-eligible if v_hat_i >= 4 m/s. "
        "Count maximal runs of consecutive eligible segments with length >= 3 segments."
    )

    sec("6) Side-to-side movement (%), lateral_movement_pct")
    blk(
        "As in compute_movement_metrics (default scale): "
        "LatAbs = sum_i |x_i - x_{i-1}|, Dist_mv = sum_i sqrt((x_i-x_{i-1})^2+(y_i-y_{i-1})^2) in court plane. "
        "lateral_pct = 100 * LatAbs / Dist_mv if Dist_mv > 0 else 0. "
        "Note: this uses normalized dx vs normalized Euclidean length; distance_m uses W,H meters."
    )

    sec("7) Hard accelerations / decelerations")
    blk(
        "From segment speeds v_i: a_i = (v_{i+1} - v_i) / dt (default dt ~ 1/30 s if not supplied). "
        "acceleration_peaks = count of a_i >= 2 m/s^2. deceleration_count = count of a_i <= -2 m/s^2."
    )

    sec("8) Time at net (%), net_pct")
    blk("net_pct = 100 * (1/N) * count of samples with y_court in [0.4, 0.6].")

    sec("9) Time deep (%), baseline_pct")
    blk("baseline_pct = 100 - net_pct (all samples not in net band, as coded).")

    sec("10) Court zones (0-5), zone_coverage_pct[z]")
    blk(
        "Each sample maps to zone Z(x,y) in {0..5} (team half A or B from y, x ignored; back/mid/net per half). "
        "zone_pct[z] = 100 * (count with Z=z) / N_p."
    )

    sec("11) Rank (1-4), rank_by_distance")
    blk("Sort players by D_p descending; rank is position (1 = most distance).")

    sec("12) Share of running (%), share_of_distance_pct")
    blk("share_p = 100 * D_p / (D_1+D_2+D_3+D_4) if denominator > 0 else 0.")

    sec("13) Heatmap (movement map)")
    blk(
        "2D histogram: for bins (u,v), count samples (x_i,y_i) falling in bin (u,v); "
        "optionally normalize by N_p for display."
    )

    sec("Data inputs")
    blk(
        "tracks.json: frame, timestamp, player_id, x_pixel, y_pixel; after stage 03 also x_court, y_court. "
        "homography.json: 3x3 H maps (x_pixel, y_pixel) to (x_court, y_court). "
        "video meta: fps, duration_seconds."
    )

    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(text_w, 4, _t("Generated by scripts/generate_player_metrics_equations_pdf.py"))

    pdf.output(str(out))
    return out


if __name__ == "__main__":
    path = main()
    print(path)
